- name: variables from PLAY level
  hosts: localhost
  vars_files:     
  - C:\Users\Dell\Desktop\DevOps Teja\Ansible\variables.yaml
  tasks: 
  - name: check variables
    ansible.builtin.debug:
      msg: "Hello My name is {{person_name}}, profession is {{profession}} , salary is {{salary}}"
      
