- name: variables from PLAY level
  hosts: localhost
  tasks: 
  - name: check variables
    ansible.builtin.debug:
      msg: "Hello My name is {{Person_name}}, profession is {{Profession}} , salary is {{Salary}}"
      
