- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: print persons
    ansible.builtin.package:
      name: "{{item}}"
      state: "{{item.state}}"
    loop:
    - {name: 'git', state: 'present'}
    - {name: 'mysql', state: 'absent'}
    - {name: 'postfix', state: 'absent'}
    - {name: 'nginx', state: 'present'}
